[[main]]
identifier = "home"
name = "Accueil"
url = "/"
weight = 1

[[main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 2

[[main]]
identifier = "posts"
name = "Articles"
url = "/posts/"
weight = 3
